### ISSUE TITLE
Allow to process non-HTML-like input in template literal with user-provided transformations to HTML

### ISSUE THREAD

**Issue by leonidborisenko** [WebReflection/domtagger#17]
There are alternative non-HTML-like syntaxes for constructing HTML documents, like:
* indent-based [Pug](https://github.com/pugjs/pug#Syntax)
* CSS-inspired [Mask](https://github.com/atmajs/MaskJS#11-mask-syntax)

Though linked libraries couldn't be used in `domtagger`'s `transform` callback, still, the syntax itself could be preferred to HTML and [partial] syntax parser could be re-implemented by user with returning parsing result as HTML string for usage within `domtagger`'s `transform` callback (and, consequently, with **lighterhtml** and **heresy**).

Unfortunately, `domtagger` unconditionally [sanitizes input](https://github.com/WebReflection/domtagger/blob/a19b392bbd8dba95380c30c5b0c387fc7cc1a122/esm/index.js#L20)  before calling `transform` and `sanitize` [expects HTML-like input](https://github.com/WebReflection/domsanitizer/blob/a874d5b56bdba1d2f6f75d43bf6a3c522ec5f9bb/index.js).

Is supporting non-HTML-like syntaxes in template literals in scope of `domtagger`?

Maybe `transform` callbacks could be stacked and any stack member could be  moved or removed with `sanitize` being added to the stack by default (as the first stack element)?

**Comment by WebReflection** [comment]
> Is supporting non-HTML-like syntaxes in template literals in scope of domtagger?

well, the library is called _DOM_ tagger for a reason, it's supposed to work with the DOM, hence HTML or SVG/XML that are all expected input.

However, since the change I have in mind would be of minimal impact, I wonder if adding `sanitize` as option would already solve your issue, so that you can pass both a `transform()` and a `sanitize()` too.

That would be `var markup = (options.sanitize || sanitize)(template);` change, so ... would that work?

**Comment by WebReflection** [comment]
P.S. after all the same way I `import sanitize from 'domsanitizer'` you could also do that in your project if/when you need the same _sanitizer_ callback ... so this looks like a no-brainer to me

**Comment by leonidborisenko** [comment]
> That would be var markup = (options.sanitize || sanitize)(template); change, so ... would that work?

> after all the same way I import sanitize from 'domsanitizer' you could also do that in your project if/when you need the same sanitizer callback ... so this looks like a no-brainer to me

I agree. This change is trivial in implementation and targets specifically the behavior I've described (non-customizable `sanitize` being called unconditionally before calling user-provided `transform` callback) from the `sanitize` customization side.

I'll just assign identity function (like `(value) => value`) to `options.sanitize` and then (as you suggested) explicitly use manually imported `domsanitizer` in `transform` callback, just before returning HTML. Looks like it should work for stuffing Pug or Mask (or any other) parser-and-converter-to-HTML into `transform` before calling `domsanitizer`.

Thanks for considering the change. If it will be implemented, will it be exposed in **lighterhtml**?

**Comment by WebReflection** [comment]
> and then (as you suggested) explicitly use manually imported domsanitizer in transform callback

just to clarify, `sanitize` will always run before `transform`. Once exported, you are free to do whatever you want within these two methods, but it's important to remember that the order is `sanitize` and then `transform`.

You are free to use only `sanitize` and do also transformations in there, but at the end of the day you'll pass through `createContent` and `cleanContent` and I am not planning to expose those too, since the whole library is supposed to work with DOM elements, so that DOM elements must be created and parsed, otherwise this is not the right library for doing what you need to do.

So, considering `var markup = (options.sanitize || sanitize)(template);` is all I am going to do, as non-breaking change, is that enough for your use case?

> will it be exposed in lighterhtml?

once we understand the change is OK and I publish the new version, it will be exposed same way `transform` is exposed now.

**Comment by WebReflection** [comment]
There is also another show-stopper for this to land, which is what `sanitize` does:
https://github.com/WebReflection/domsanitizer/blob/master/esm/index.js

The returned text **must** contain comments with the expected `domconstant` `UID` for attributes content and `UIDC` for comments within DOM nodes.

These two are crucial to know where the template tag holes end up in the produced output, so that any sanitizer that doesn't return those values correctly will fail.

I think exposing _sanitizer_ will cause more troubles than solutions to those that will try it, yet I don't see why I shouldn't enable it if critical for 3rd parts.

Although, I am thinking to keep the new export undocumented, 'cause explaining the whole sanitization needed for this library to work seems to be a bit too much, and it's also not a common use case.

**Comment by WebReflection** [comment]
as food for thoughts:

```js
import domtagger from 'domtagger';
import sanitize from 'domsanitizer';
import pug from 'pug';

const UID = Math.random() * Date.now();

const magic = domtagger({
  // sanitize the transformation of pug content as HTML
  // preserving all the holes parts where these are already
  sanitize: template => sanitize(pug.toHTML(template.join(UID)).split(UID))
});
```

Something like that might work (I don't know about `pug` so `toHTML` is just a hint) and since this is the one off part per template literal this library optimizes for, it might also keep performance super high.

Deal?

**Comment by leonidborisenko** [comment]
> just to clarify, sanitize will always run before transform. Once exported, you are free to do whatever you want within these two methods, but it's important to remember that the order is sanitize and then transform.

Yes, I understand this.

Currently, calling fixed `sanitize` function (which expects valid HTML as an input) is a problem because it is called before `transform` **and** it couldn't be avoided or changed or replaced. If it will be replaceable (this is what you are suggesting) **and** default `sanitize` would be available as a separate function (just as it is already), then order would be not significant for me.

> You are free to use only sanitize and do also transformations in there, but at the end of the day you'll pass through createContent and cleanContent and I am not planning to expose those too, since the whole library is supposed to work with DOM elements, so that DOM elements must be created and parsed, otherwise this is not the right library for doing what you need to do.

> There is also another show-stopper for this to land, which is what sanitize does:
https://github.com/WebReflection/domsanitizer/blob/master/esm/index.js
>
> The returned text must contain comments with the expected domconstant UID for attributes content and UIDC for comments within DOM nodes.

Scheme I have in mind uses `transform` callback (but using `sanitize` callback is good too). In this scheme user-provided `transform` receives strings from template literal (containing specific non-HTML syntax)  and returns string with valid HTML (conforming to any `domtagger` requirements, if there are any). So, I guess, I have no need to change any `domtagger`'s HTML input expectation (and no need to have a way to customize any `domtagger`s behavior) as long as it happens after calling `transform`.

> So, considering var markup = (options.sanitize || sanitize)(template); is all I am going to do, as non-breaking change, is that enough for your use case?

Yes, I believe it is enough.

> `sanitize: template => sanitize(pug.toHTML(template.join(UID)).split(UID))`
>
> Something like that might work (I don't know about pug so toHTML is just a hint) and since this is the one off part per template literal this library optimizes for, it might also keep performance super high.
> 
> Deal?

Yes, I believe this is exactly the scheme I want. Thanks for code example. (Even if Pug library couldn't be used in such way, Pug [subset] parser or any other parser could be re-implemented).

**Comment by leonidborisenko** [comment]
Just a thought: maybe `options` field should be named not specifically `options.sanitize` but a bit more general.

After all this is practically the same `transform` callback, but its' contract is a bit different. `transform` expects HTML and returns HTML. But this new callback expects any syntax and returns HTML.

I have no suggestions about naming and I'm good with `options.sanitize`.

OK, I see, I am late and it's already implemented as `options.sanitize`. :) Still, even if it's not up to discussion already, it might be something worth considering given that now there are no users relying on this concrete name.

**Comment by WebReflection** [comment]
it's a very poorly documented feature with a background that is about sanitizing the template input to produce well formed HTML output, so I hope you don't mind me keeping it consistent with the name `domsanitizer` module has already, 'cause changing here, would mean changing the other library, but all of this is very _edgy_, so I hope we can all cope with my previously badly chosen name.

**lighterhtml** 1.0.3 already exposes this, please let me know how that goes.

**Comment by WebReflection** [comment]
btw, if you have a better, very meaningful, name for that, I might just use it as object property, since that doesn't really care about domtagger internals ... so please, suggest, until it's fresh new change in the patch level of the module, thanks!

**Comment by WebReflection** [comment]
P.S. `template2properlyFormedHTMLWithHolesPreservedAsUIDs` doesn't look a good alternative 😂

**Comment by leonidborisenko** [comment]
> it's a very poorly documented feature with a background that is about sanitizing the template input to produce well formed HTML output, so I hope you don't mind me keeping it consistent with the name domsanitizer module has already, 'cause changing here, would mean changing the other library, but all of this is very edgy, so I hope we can all cope with my previously badly chosen name.

Even though I can recognize humor, it's hard to decide whether you answered ironically (sarcastically?) or seriously. But given that your motivation is, probably, partially based on constructive feedback from users, I want to say that I had no intentions to offend you or anything. Sorry, if I said something offending.

Anyway, I'm totally OK with `options.sanitize`.

> lighterhtml 1.0.3 already exposes this, please let me know how that goes.

Thanks a lot, I'll try and report here later.

> btw, if you have a better, very meaningful, name for that, I might just use it as object property, since that doesn't really care about domtagger internals ... so please, suggest, until it's fresh new change in the patch level of the module, thanks!
> P.S. template2properlyFormedHTMLWithHolesPreservedAsUIDs doesn't look a good alternative joy

I agree, it's hard to name this callback and `sanitize` has a head-start by being the description of what this callback currently does by default.

I had that thought about naming, because it turned out to be more appealing to use this callback to transform arbitrary syntax to HTML and leave `transform` not defined (as in your code example) instead of assigning `(value) => value` to this callback and using `transform` to actually do parsing.

But then sanitizing is just one of a callback implementation details.

So, generally speaking, this callback is the first action ever done on input, and it must return valid HTML conforming also to specific `domtagger` requirements.

As this is an user-provided callback, template literal used as an input can contain non-HTML, user-defined syntax processed by this callback into conforming HTML.

When template literal contains HTML, this callback is, probably, will not be redefined by user, because transforming HTML can be done in `transform` callback.

Maybe something like `parse` or `parseToHtml` or `parseInputToConformingHtml` would work?

**Comment by WebReflection** [comment]
@leonidborisenko by no mean I got offended or I was sarcastic there, `domsanitizer` is really a bad name for something that doesn't deal directly with DOM, accepts a template literal tag Array, and produces a (eventually) sanitized output as string ... it would've been meaningful only producing such output from a generic string, or sanitizing some corrupted node, through its DOM prefix.

All I am saying is that I didn't really pay enough attention to its name, which was intended for internal usage only, and I agree `sanitize` is not the most out-of-the-box self-explanatory name.

> it turned out to be more appealing to use this callback to transform arbitrary syntax to HTML and leave transform not defined (as in your code example) instead of assigning (value) => value to this callback and using transform to actually do parsing.

Well, `transform` is needed by _heresy_ to easily change `CustomElement` into `<custom-element>` or `<div is="custom-element">`, and it's based on the assumption that the HTML passed to transform is already sanitized/good for _heresy_ needs.

That's it, `transform` passes an already valid HTML that could be changed from third parts, while `sanitize`, which was internal only, was supposed to produce such well formed, expected, layout.

These two methods are completely different indeed, one is to create sanitized HTML, the other one is to quickly patch such sanitized layout before being interpreted as HTML content.

> As this is an user-provided callback, template literal used as an input can contain non-HTML, user-defined syntax processed by this callback into conforming HTML.

Correct, as long as the resulting HTML string is valid, and it contains all the information to find the template tag literals holes in it, you are free to use it.

Transform would eventually be used by third parts of your third part library that sanitizes upfront, if you expose the transform mechanism.

Again, these two are not even similar in their intent, but the naming might be confusing, specially in the `sanitize` case.

> Maybe something like parse or parseToHtml or parseInputToConformingHtml would work?

Internally, `parse` is the function that actually parses the DOM, so it's confusing to read `outcome = options.parse(something)` followed by `parse(outcome)` to me, but then again, the `sanitize` goal is not really to _parse_ things, rather to create valid HTML from an Array of values, preserving its holes through the _domtagger_ holes convention, either as attributes, or content.

```js
html`<p test=${1}>${2}</p>`;

// the sanitize makes the following array
['<p test=', '>', '</p>']

// producing the following HTML
'<p test="uid"><!--uid--></p>'
```
so that _domtagger_ can address those `uid`s and react accordingly on each update.

I know that _sanitize_ does now looks like another `transform`, but `transform` meaning was clear since the beginning, as you can transform sanitized HTML already, so that we need to eventually come up with a better name.

Again, these are all details that library users couldn't care less, 'cause all they use is `html`, `svg`, and `render`.

**Comment by WebReflection** [comment]
P.S. on a second though, `transform` should've been named `patch`, and `sanitize` should've been named `transform` ... I guess it's a bit too late for that, unless I do a major release only to change these names (not because of `sanitize`, just because `transform` is our already).

**Comment by leonidborisenko** [comment]
> That's it, transform passes an already valid HTML that could be changed from third parts, while sanitize, which was internal only, was supposed to produce such well formed, expected, layout.
> 
> These two methods are completely different indeed, one is to create sanitized HTML, the other one is to quickly patch such sanitized layout before being interpreted as HTML content.
>
> Internally, parse is the function that actually parses the DOM, so it's confusing to read outcome = options.parse(something) followed by parse(outcome) to me, but then again, the sanitize goal is not really to parse things, rather to create valid HTML from an Array of values, preserving its holes through the domtagger holes convention, either as attributes, or content.

I agree, `parse` is confusing. And your description in last paragraph is helpfully precise, thanks for that.

Maybe, something like:
* `createHtml`
* `produceHtml`
* `convertToHtml`
* `constructHtml`
* `templateToHtml`
* `convertTemplateStringsToHtml`
* `htmlifyTemplateLiteral`
* `staticPrerender`

Yep, this is really hard.

I hope, I'm not beating a dead horse. By answering I don't intend to push some new name, just want to add a little to possibly helpful brainstorming (to find a name that will be a bit more general while, at the same time,  being clear and relevant to possible use-cases and callback result), even though my suggestions might not be accepted or noted (it's totally OK for me).

**Comment by WebReflection** [comment]
`templateToHtml` seems a good candidate, but the key here is that such HTML *must* preserve holes with a predefined convention.

That's it, unless it's clear from the method that is the way to not break things _domtagger_ expects to find in the resulting HTML, any name would be misleading, hence I rather use a vague, misleading, name upfront so that whoever is willing to use it, needs to know all the caveats around it.

Accordingly, I feel like using a self-explanatory name for something that is not really explained through such name, would be worse than having a vague name everyone needs to investigate about.

I've just exposed an internal, through a not-really-famous library (and its bad name), and I don't want to tell anyone "_just override my stuff, you'll be good_" 'cause that's not nearly representing the story.

`templateToHoledHTML` might be a better choice to summarize what the method is meant to be ... do you think it's any better than `sanitize`?

**Comment by WebReflection** [comment]
P.S. `converter` might also imply you need to know the does and dont's, keeping its meaning semantic. Paired with `transform` might feel like too much of a brain muscle to remember, but then again, these two methods do different things, yet these both _transform_ or _convert_ something into something else.

**Comment by WebReflection** [comment]
P.P.S. since `transform` is imperative, `convert` might also be a better name

**Comment by leonidborisenko** [comment]
> lighterhtml 1.0.3 already exposes this, please let me know how that goes.

So, it appears, using existing HTML template libraries with alternative syntaxes is practically impossible in `sanitize` callback, because they want to parse whole template in one step and return whole render result with interpolated values. Workarounds with joining `sanitize` callback parameter, processing it and splitting back are brittle, given that it's not obvious how to choose concrete join separator conforming to alternative syntax, and how to force HTML template library to support that separator in any place inside template and somehow preserve join separator in its' render output.

But I'm just reporting it as a progress checkpoint, not as an another issue.

This **issue is resolved** for me, because working with array of strings is understandable requirement and, I think, I can implement parser (to use in `sanitaize` callback) which accepts array of strings and returns array of strings (to pass to  default `sanitize` from `domsanitizer`).

Thanks a lot for implementing this change.

**Comment by WebReflection** [comment]
> So, it appears, using existing HTML template libraries with alternative syntaxes is practically impossible in sanitize callback

... I don't want to say "_told'ya so_" .... but:

> I think exposing sanitizer will cause more troubles than solutions to those that will try it

Yes, the sanitizer function does something complicated, forged in such way after dozen issues found in this or that browser, incapable of having a common UID that would've worked for both attributes, without throwing random errors in console, or comments, without having ambiguous results.

However, "_practically impossible_" is a bit harsh as conclusion, as I've already told you how to recycle the current sanitize function, so that all you need to do is, accordingly with the 3rd parts library you want to use, is to find similar compromise and return back the Array as it was.

This is how tag template literals work, and the mapping between holes and updates is essential to make any of this work, which is how _hyperHTML_ was born, and how it worked for the last ~2 years.

Yet, I am curious to know if `convert` would be a better name candidate for `sanitize`, considering everything else will be exactly the same as is now, it's just the exposed name/override that might make more meaningful sense.

**Comment by WebReflection** [comment]
anyway, after all these exchanges I think I'll go right away with `convert` so that there will likely be less discussions in the future about what that is, or what that does.

**Comment by WebReflection** [comment]
so ... 1.0.4 has `convert` instead of `sanitize`, I hope this is better/OKish now

**Comment by leonidborisenko** [comment]
> templateToHtml seems a good candidate, but the key here is that such HTML must preserve holes with a predefined convention.
>
> That's it, unless it's clear from the method that is the way to not break things domtagger expects to find in the resulting HTML, any name would be misleading, hence I rather use a vague, misleading, name upfront so that whoever is willing to use it, needs to know all the caveats around it.

Right, I understand this.

> templateToHoledHTML might be a better choice to summarize what the method is meant to be ... do you think it's any better than sanitize?

Yeah, actually I do think it's better than `sanitize`. Though "holed" bit isn't precisely descriptive, because, while it understandably describes the purpose ("hole" being a name for static placeholder to be filled with dynamic value), this is pretty rare name for plain HTML comment. And "holed" can be confusing adjective for string result of callback ("holed" string?).

Or I'm just bikeshedding here?.. I guess "hole" can be easily related to `${}` "hole" in template literal and, anyway, what is a "hole" exactly means and how it must be represented in output HTML can be explained in API comment.

Maybe `templateToInterpolatableHtml` or `templateToPrerenderHtml`? It's more vague than holed, but points to output HTML being in unfinished state. Or `templateToPlaceholderedHtml`? `templateToFillableHtml`?

**Comment by leonidborisenko** [comment]
> so ... 1.0.4 has convert instead of sanitize, I hope this is better/OKish now

It's better and it's OK for me.

**Comment by leonidborisenko** [comment]
> ... I don't want to say "told'ya so" .... but:
>
 > >   I think exposing sanitizer will cause more troubles than solutions to those that will try it

No, it made some my use-cases possible. Some troubles are real now, but they are completely mine. Some (hard?) work is required from me to make something usable, but it was expected. I didn't expect immediate results and now, at least, I can implement some useful scenarios which I couldn't implement before this change.

> Yes, the sanitizer function does something complicated, forged in such way after dozen issues found in this or that browser, incapable of having a common UID that would've worked for both attributes, without throwing random errors in console, or comments, without having ambiguous results.

Thanks for clarification. I'm planning to reuse default `sanitize` (callback parameter) for its' part of work. I'll just pass new array (with parsing result) to it.

> However, "practically impossible" is a bit harsh as conclusion, as I've already told you how to recycle the current sanitize function, so that all you need to do is, accordingly with the 3rd parts library you want to use, is to find similar compromise and return back the Array as it was.
>
> This is how tag template literals work, and the mapping between holes and updates is essential to make any of this work, which is how hyperHTML was born, and how it worked for the last ~2 years.

I understand. 

`practically impossible` part wasn't a critic of `domtagger` or any other 3rd-party librariy. It's just description of my current skills. Or maybe it's a rationalization of NIH syndrome, because I want to build a parser more suitable to use with `domtagger`.
